---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-api
  labels:
    app.kubernetes.io/name: shopping-api
    app.kubernetes.io/instance: shopping-api
data:
  DB_HOST: "trainingdb.sh9qggf.mongodb.net"
  DB_USER: "prodrw"
