---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-api
  labels:
    app.kubernetes.io/name: shopping-api
    app.kubernetes.io/instance: shopping-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shopping-api
      app.kubernetes.io/instance: shopping-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shopping-api
        app.kubernetes.io/instance: shopping-api
    spec:
      containers:
        - name: shopping-api
          image: "shopping-api:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: APP_SERVER_PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: shopping-api
            - secretRef:
                name: shopping-api
          livenessProbe:
            httpGet:
              path: /products
              port: http
          readinessProbe:
            httpGet:
              path: /products
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-api
  labels:
    app.kubernetes.io/name: shopping-api
    app.kubernetes.io/instance: shopping-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: shopping-api
    app.kubernetes.io/instance: shopping-api
