apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopping-api.fullname" . }}
  labels:
    {{- include "shopping-api.labels" . | nindent 4 }}
data:
  {{- with .Values.configs }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
