apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: shopping-api
    literals:
      - DB_HOST=trainingdb.sh9qggf.mongodb.net
      - DB_USER=prodrw
